services:
  api:
    build:
      context: .
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - sqlserver
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  sqlserver:
    build:
      context: .
      dockerfile: docker/sqlserver/Dockerfile
    environment:
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      SQLSERVER_DB: ${SQLSERVER_DB}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
