name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff
        run: |
          TARGETS="app/logging.py app/notify/dispatcher.py app/notify/repository.py app/notify/worker.py app/api/notifications.py app/models.py tests/test_dispatcher.py tests/test_notifications_api.py"
          ruff check $TARGETS
      - name: Black
        run: |
          TARGETS="app/logging.py app/notify/dispatcher.py app/notify/repository.py app/notify/worker.py app/api/notifications.py app/models.py tests/test_dispatcher.py tests/test_notifications_api.py"
          black --check $TARGETS

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Pytest
        run: pytest

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t prl-notifier:ci .
